domain: library.canonical.com

image: prod-comms.ps5.docker-registry.canonical.com/library.canonical.com

env:
  - name: SENTRY_DSN
    value: https://3c9a25a1976d4a97981997bb5a1ca7b4@sentry.is.canonical.com//28

  - name: PRIVATE_KEY_ID
    secretKeyRef:
      key: private-key-id
      name: library-canonical-com

  - name: PRIVATE_KEY
    secretKeyRef:
      key: private-key
      name: library-canonical-com

  - name: PROJECT_ID
    secretKeyRef:
      key: project-id
      name: library-canonical-com

  - name: CLIENT_EMAIL
    secretKeyRef:
      key: client-email
      name: library-canonical-com

  - name: CLIENT_ID
    secretKeyRef:
      key: client-id
      name: library-canonical-com

  - name: CLIENT__X509_CERT_URL
    secretKeyRef:
      key: client-x509-cert-url
      name: library-canonical-com

# Overrides for production
production:
  replicas: 5
  nginxConfigurationSnippet: |
    if ($host != 'library.canonical.com' ) {
      rewrite ^ https://library.canonical.com$request_uri? permanent;
    }
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";

# Overrides for staging
staging:
  replicas: 3
  nginxConfigurationSnippet: |
    more_set_headers "X-Robots-Tag: noindex";
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";
