domain: library.canonical.com

image: prod-comms.docker-registry.canonical.com/library.canonical.com

useProxy: true

env:
  - name: SENTRY_DSN
    value: https://3c9a25a1976d4a97981997bb5a1ca7b4@sentry.is.canonical.com//28

  - name: SEARCH_API_KEY
    secretKeyRef:
      key: google-custom-search-key
      name: google-api

# Overrides for production
production:
  replicas: 5
  nginxConfigurationSnippet: |
    if ($host != 'library.canonical.com' ) {
      rewrite ^ https://library.canonical.com$request_uri? permanent;
    }
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";
  nginxServerSnippet: |
    location ^~ /install/ {
      rewrite ^/install/(.*).exe /ubuntu/library-canonical/releases/download/installer-$1/library-canonical-installer.exe break;
      proxy_pass https://github.com/;
    }

# Overrides for staging
staging:
  replicas: 3
  nginxConfigurationSnippet: |
    more_set_headers "X-Robots-Tag: noindex";
    more_set_headers "Link: <https://assets.ubuntu.com>; rel=preconnect; crossorigin, <https://assets.ubuntu.com>; rel=preconnect";
  nginxServerSnippet: |
    location /install/ {
      rewrite ^/install/(.*).exe /ubuntu/library-canonical/releases/download/installer-$1/library-canonical-installer.exe break;
      proxy_pass https://github.com/;
    }
